name: Formatter

on:
  push:
    branches: ["**", "!main"]

jobs:
  format-code:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install Hatch
        uses: pypa/hatch@install

      - name: Format
        run: hatch run lint:fmt

      - name: Commit changes if needed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-format code"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
